### ISSUE TITLE
problème lab3 | part3 | accéléromètre

### ISSUE THREAD

**Issue by Hajar-B** [institut-galilee/Les-Licornes#2]
Bonjour monsieur, nous avons constaté un problème lors du téléversement du code plotter pour l'accéléromètre. Nous n'avons pas pu résoudre ce problème voici l'erreur :

Arduino : 1.8.10 (Windows 10), Carte : "Arduino/Genuino Uno"

Plusieurs bibliothèque trouvées pour "Adafruit_MPU6050.h"
In file included from C:\Users\TEMP.SERCAL\Documents\Arduino\libraries\Adafruit_MPU6050/Adafruit_MPU6050.h:21:0,

Utilisé : C:\Users\TEMP.SERCAL\Documents\Arduino\libraries\Adafruit_MPU6050
                 from C:\Users\TEMP~1.SER\AppData\Local\Temp\arduino_modified_sketch_167774\plotter.ino:3:

C:\Users\TEMP.SERCAL\Documents\Arduino\libraries\Adafruit_MPU6050/Adafruit_BusIO_Register.h:1:10: fatal error: Adafruit_I2CDevice.h: No such file or directory

 #include <Adafruit_I2CDevice.h>

          ^~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1
Erreur de compilation pour la carte Arduino/Genuino Uno

Ce rapport pourrait être plus détaillé avec
l'option "Afficher les résultats détaillés de la compilation"
activée dans Fichier -> Préférences.

**Comment by HamidiMassinissa** [comment]
Bonjour,
je voudrais bien avoir la sortie en mode verbose. Peux-tu activer l'option en question et me redonner la sortie. Mais avant cela, essaye d'installer Adafruit BusIO via le gestionnaire de bibliothèques.
